### ISSUE TITLE
Manejar los estados de los filtros

### ISSUE THREAD

**Issue by beresiartejuan** [CodeStrong2023/EcommerceHolaMundoAnimal#4]
Dentro del archivo `/src/client/index.html` hay una serie de filtros dentro de un elemento div con la clase "filter-container". Se debe crear un codigo en javascript para que el acceso a su estado sea simple y posteriormente se pueda cambiar los resultados utilizando los filtros.

**Comment by AdrianaVB** [comment]
Está agregada la carpeta filtro al proyecto

**Comment by AdrianaVB** [comment]
Actualizado
