### ISSUE TITLE
Hacer que los filtros funcionen

### ISSUE THREAD

**Issue by beresiartejuan** [CodeStrong2023/EcommerceHolaMundoAnimal#5]
Se debe esperar a que [esta issue](https://github.com/CodeStrong2023/EcommerceHolaMundoAnimal/issues/4) este terminada y modificar el contenido dentro del elemento `section` con el id "products" teniendo en cuenta los filtros de precio y tipo ignorando el filtro "sub-categorías".

Para filtrar por tipo se deberá verificar si en el nombre del producto se encuentra la palabra "perro" o "gato"

**Comment by AdrianaVB** [comment]
PROPUESTA DE SISTEMA DE FILTRO DE PRODUCTOS: donde los usuarios pueden buscar productos en una lista utilizando un campo de texto

**Comment by AdrianaVB** [comment]
Actualizado

**Comment by AdrianaVB** [comment]
Actualizado y funciona
